name: "Build and deploy Node.js app to Azure Web App"

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install --force

      # Uncomment the next step to run tests
      # - name: Run tests
      #   run: npm test

      - name: Build project
        run: npm run build

      - name: Archive build artifacts
        run: tar -czf build.tar.gz -C build .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Extract artifact
        run: tar -xzf build.tar.gz

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8105F3456E7D415F8E664558247D6FDE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_66C0316A015240E9B6C5853B9C446272 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F95578B0C9A74D649B3261454A0A7934 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'doccollecttest'
          slot-name: 'Production'
          package: .
